CICD test 9

diff --git a/.github/workflows/aws.yaml b/.github/workflows/aws.yaml
--- a/.github/workflows/aws.yaml
+++ b/.github/workflows/aws.yaml
@@ -54,10 +54,17 @@ jobs:
 
       - name: Run Docker Image to serve users
         run: |
+          IMAGE="${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:latest"
+          
+          # Optional safety check
+          if [ -z "$IMAGE" ]; then
+            echo "ERROR: Docker image is not defined."
+            exit 1
+          fi
+      
           docker stop app || true
           docker rm app || true
-          IMAGE="${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:latest"
-          echo "Docker image: $IMAGE"
+      
           docker run -d --name app \
             -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
             -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
